set_attack_value(AT_DSTRONG, AG_SPRITE, sprite_get("dstrong"));
set_attack_value(AT_DSTRONG, AG_NUM_WINDOWS, 3);
set_attack_value(AT_DSTRONG, AG_STRONG_CHARGE_WINDOW, 1);
set_attack_value(AT_DSTRONG, AG_HURTBOX_SPRITE, sprite_get("dstrong_hurt"));

set_window_value(AT_DSTRONG, 1, AG_WINDOW_TYPE, 1);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_LENGTH, 6);
set_window_value(AT_DSTRONG, 1, AG_WINDOW_ANIM_FRAMES, 1);

set_window_value(AT_DSTRONG, 2, AG_WINDOW_TYPE, 1);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_LENGTH, 16);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_ANIM_FRAMES, 4);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_ANIM_FRAME_START, 1);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_HAS_SFX, 1);
set_window_value(AT_DSTRONG, 2, AG_WINDOW_SFX, asset_get("sfx_swipe_heavy2"));

set_window_value(AT_DSTRONG, 3, AG_WINDOW_TYPE, 1);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_LENGTH, 16);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_ANIM_FRAMES, 1);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_ANIM_FRAME_START, 5);
set_window_value(AT_DSTRONG, 3, AG_WINDOW_HAS_WHIFFLAG, 1);

set_num_hitboxes(AT_DSTRONG, 9);

//Hit 1
set_hitbox_value(AT_DSTRONG, 1, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 1, HG_WINDOW, 2);
set_hitbox_value(AT_DSTRONG, 1, HG_LIFETIME, 4);
set_hitbox_value(AT_DSTRONG, 1, HG_HITBOX_X, 5);
set_hitbox_value(AT_DSTRONG, 1, HG_HITBOX_Y, -17);
set_hitbox_value(AT_DSTRONG, 1, HG_WIDTH, 40);
set_hitbox_value(AT_DSTRONG, 1, HG_HEIGHT, 45);
set_hitbox_value(AT_DSTRONG, 1, HG_SHAPE, 2);
set_hitbox_value(AT_DSTRONG, 1, HG_PRIORITY, 2);
set_hitbox_value(AT_DSTRONG, 1, HG_DAMAGE, 3);
set_hitbox_value(AT_DSTRONG, 1, HG_ANGLE, 35);
set_hitbox_value(AT_DSTRONG, 1, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DSTRONG, 1, HG_BASE_KNOCKBACK, 5);
set_hitbox_value(AT_DSTRONG, 1, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_DSTRONG, 1, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_DSTRONG, 1, HG_TECHABLE, 1);
set_hitbox_value(AT_DSTRONG, 1, HG_HITBOX_GROUP, 1);

//Hit 2
set_hitbox_value(AT_DSTRONG, 2, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 2, HG_WINDOW, 2);
set_hitbox_value(AT_DSTRONG, 2, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_DSTRONG, 2, HG_LIFETIME, 4);
set_hitbox_value(AT_DSTRONG, 2, HG_HITBOX_X, 35);
set_hitbox_value(AT_DSTRONG, 2, HG_HITBOX_Y, -17);
set_hitbox_value(AT_DSTRONG, 2, HG_WIDTH, 30);
set_hitbox_value(AT_DSTRONG, 2, HG_HEIGHT, 45);
set_hitbox_value(AT_DSTRONG, 2, HG_SHAPE, 2);
set_hitbox_value(AT_DSTRONG, 2, HG_PRIORITY, 2);
set_hitbox_value(AT_DSTRONG, 2, HG_DAMAGE, 3);
set_hitbox_value(AT_DSTRONG, 2, HG_ANGLE, 35);
set_hitbox_value(AT_DSTRONG, 2, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_DSTRONG, 2, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_DSTRONG, 2, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_DSTRONG, 2, HG_TECHABLE, 1);
set_hitbox_value(AT_DSTRONG, 2, HG_HITBOX_GROUP, 2);

set_hitbox_value(AT_DSTRONG, 3, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 3, HG_WINDOW, 2);
set_hitbox_value(AT_DSTRONG, 3, HG_WINDOW_CREATION_FRAME, 4);
set_hitbox_value(AT_DSTRONG, 3, HG_LIFETIME, 4);
set_hitbox_value(AT_DSTRONG, 3, HG_HITBOX_X, -23);
set_hitbox_value(AT_DSTRONG, 3, HG_HITBOX_Y, -17);
set_hitbox_value(AT_DSTRONG, 3, HG_WIDTH, 30);
set_hitbox_value(AT_DSTRONG, 3, HG_HEIGHT, 45);
set_hitbox_value(AT_DSTRONG, 3, HG_SHAPE, 2);
set_hitbox_value(AT_DSTRONG, 3, HG_PRIORITY, 2);
set_hitbox_value(AT_DSTRONG, 3, HG_DAMAGE, 3);
set_hitbox_value(AT_DSTRONG, 3, HG_ANGLE, 35);
set_hitbox_value(AT_DSTRONG, 3, HG_ANGLE_FLIPPER, 5);
set_hitbox_value(AT_DSTRONG, 3, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_DSTRONG, 3, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_DSTRONG, 3, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_DSTRONG, 3, HG_TECHABLE, 1);
set_hitbox_value(AT_DSTRONG, 3, HG_HITBOX_GROUP, 2);

//Hit 3
set_hitbox_value(AT_DSTRONG, 4, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 4, HG_WINDOW, 2);
set_hitbox_value(AT_DSTRONG, 4, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_DSTRONG, 4, HG_LIFETIME, 4);
set_hitbox_value(AT_DSTRONG, 4, HG_HITBOX_X, 50);
set_hitbox_value(AT_DSTRONG, 4, HG_HITBOX_Y, -32);
set_hitbox_value(AT_DSTRONG, 4, HG_WIDTH, 38);
set_hitbox_value(AT_DSTRONG, 4, HG_HEIGHT, 75);
set_hitbox_value(AT_DSTRONG, 4, HG_SHAPE, 2);
set_hitbox_value(AT_DSTRONG, 4, HG_PRIORITY, 2);
set_hitbox_value(AT_DSTRONG, 4, HG_DAMAGE, 6);
set_hitbox_value(AT_DSTRONG, 4, HG_ANGLE, 40);
set_hitbox_value(AT_DSTRONG, 4, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DSTRONG, 4, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_DSTRONG, 4, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_DSTRONG, 4, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_DSTRONG, 4, HG_TECHABLE, 1);
set_hitbox_value(AT_DSTRONG, 4, HG_HITBOX_GROUP, 3);
	
set_hitbox_value(AT_DSTRONG, 5, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 5, HG_WINDOW, 2);
set_hitbox_value(AT_DSTRONG, 5, HG_WINDOW_CREATION_FRAME, 8);
set_hitbox_value(AT_DSTRONG, 5, HG_LIFETIME, 4);
set_hitbox_value(AT_DSTRONG, 5, HG_HITBOX_X, -38);
set_hitbox_value(AT_DSTRONG, 5, HG_HITBOX_Y, -32);
set_hitbox_value(AT_DSTRONG, 5, HG_WIDTH, 38);
set_hitbox_value(AT_DSTRONG, 5, HG_HEIGHT, 75);
set_hitbox_value(AT_DSTRONG, 5, HG_SHAPE, 2);
set_hitbox_value(AT_DSTRONG, 5, HG_PRIORITY, 2);
set_hitbox_value(AT_DSTRONG, 5, HG_DAMAGE, 6);
set_hitbox_value(AT_DSTRONG, 5, HG_ANGLE, 40);
set_hitbox_value(AT_DSTRONG, 5, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DSTRONG, 5, HG_BASE_KNOCKBACK, 3);
set_hitbox_value(AT_DSTRONG, 5, HG_BASE_HITPAUSE, 6);
set_hitbox_value(AT_DSTRONG, 5, HG_HIT_SFX, asset_get("sfx_blow_medium2"));
set_hitbox_value(AT_DSTRONG, 5, HG_TECHABLE, 1);
set_hitbox_value(AT_DSTRONG, 5, HG_HITBOX_GROUP, 3);

//Hit 4
set_hitbox_value(AT_DSTRONG, 6, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 6, HG_WINDOW, 2);
set_hitbox_value(AT_DSTRONG, 6, HG_WINDOW_CREATION_FRAME, 12);
set_hitbox_value(AT_DSTRONG, 6, HG_LIFETIME, 4);
set_hitbox_value(AT_DSTRONG, 6, HG_HITBOX_X, 60);
set_hitbox_value(AT_DSTRONG, 6, HG_HITBOX_Y, -42);
set_hitbox_value(AT_DSTRONG, 6, HG_WIDTH, 42);
set_hitbox_value(AT_DSTRONG, 6, HG_HEIGHT, 95);
set_hitbox_value(AT_DSTRONG, 6, HG_SHAPE, 2);
set_hitbox_value(AT_DSTRONG, 6, HG_PRIORITY, 2);
set_hitbox_value(AT_DSTRONG, 6, HG_DAMAGE, 7);
set_hitbox_value(AT_DSTRONG, 6, HG_ANGLE, 40);
set_hitbox_value(AT_DSTRONG, 6, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DSTRONG, 6, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_DSTRONG, 6, HG_KNOCKBACK_SCALING, 0.85);
set_hitbox_value(AT_DSTRONG, 6, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_DSTRONG, 6, HG_HITPAUSE_SCALING, 0.95);
set_hitbox_value(AT_DSTRONG, 6, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));
set_hitbox_value(AT_DSTRONG, 6, HG_HITBOX_GROUP, 4);

set_hitbox_value(AT_DSTRONG, 7, HG_HITBOX_TYPE, 1);
set_hitbox_value(AT_DSTRONG, 7, HG_WINDOW, 2);
set_hitbox_value(AT_DSTRONG, 7, HG_WINDOW_CREATION_FRAME, 12);
set_hitbox_value(AT_DSTRONG, 7, HG_LIFETIME, 4);
set_hitbox_value(AT_DSTRONG, 7, HG_HITBOX_X, -48);
set_hitbox_value(AT_DSTRONG, 7, HG_HITBOX_Y, -42);
set_hitbox_value(AT_DSTRONG, 7, HG_WIDTH, 42);
set_hitbox_value(AT_DSTRONG, 7, HG_HEIGHT, 95);
set_hitbox_value(AT_DSTRONG, 7, HG_SHAPE, 2);
set_hitbox_value(AT_DSTRONG, 7, HG_PRIORITY, 2);
set_hitbox_value(AT_DSTRONG, 7, HG_DAMAGE, 7);
set_hitbox_value(AT_DSTRONG, 7, HG_ANGLE, 40);
set_hitbox_value(AT_DSTRONG, 7, HG_ANGLE_FLIPPER, 6);
set_hitbox_value(AT_DSTRONG, 7, HG_BASE_KNOCKBACK, 8);
set_hitbox_value(AT_DSTRONG, 7, HG_KNOCKBACK_SCALING, 0.85);
set_hitbox_value(AT_DSTRONG, 7, HG_BASE_HITPAUSE, 7);
set_hitbox_value(AT_DSTRONG, 7, HG_HITPAUSE_SCALING, 0.95);
set_hitbox_value(AT_DSTRONG, 7, HG_HIT_SFX, asset_get("sfx_blow_heavy2"));
set_hitbox_value(AT_DSTRONG, 7, HG_HITBOX_GROUP, 4);